Controllers/AdminController.cs
using BillAdmin.DataBaseAccess;
using BillAdmin.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;
///===============================================================
/// <summary>
/// FileName : AdminController.cs
/// Description : 관리자 관련 탭 컨트롤러
/// Copyright : 2020 by PayLetter Inc. All rights reserved.
/// Author : mh_kim@payletter.com, 2020-11-10
/// Modify History : Just Created.
/// </summary>
///================================================================
namespace BillAdmin.Controllers
{
    public class AdminController : Controller
    {
        AccountDAO objActDao = new AccountDAO();
        AdminDAO objAdminDao = new AdminDAO();

        /// -------------------------------------------------------
        /// <summary>
        /// 관리자 리스트
        /// </summary>
        /// -------------------------------------------------------
        public ActionResult AdminFrm()
        {
            DataSet ds = objActDao.SearchAdminDetailInfo("");
            ViewBag.adminList = ds.Tables[0];
            return View();
        }

        [HttpPost]
        public ActionResult AdminFrm(string strAdminId)
        {
            DataSet ds = objActDao.SearchAdminDetailInfo(strAdminId);
            ViewBag.adminList = ds.Tables[0];
            return View();
        }

        /// -------------------------------------------------------
        /// <summary>
        /// 실시간 세션 리스트
        /// </summary>
        /// -------------------------------------------------------
        public ActionResult SessionLstFrm()
        {
            DataSet ds = objAdminDao.SearchAdminSessionLst("", "");
            ViewBag.sesionList = ds.Tables[0];
            return View();
        }

        [HttpPost]
        public ActionResult SessionLstFrm(string strAdminId, string strIPAddr)
        {
            DataSet ds = objAdminDao.SearchAdminSessionLst(strAdminId, strIPAddr);
            ViewBag.sesionList = ds.Tables[0];
            return View();
        }
        /// -------------------------------------------------------
        /// <summary>
        /// 로그인 세션 이력 리스트
        /// </summary>
        /// -------------------------------------------------------
        public ActionResult LoginSessionLstFrm()
        {
            DataSet ds = objAdminDao.SearchAdminLoginSessionLst("", "");
            ViewBag.loginSesionList = ds.Tables[0];
            return View();
        }

        [HttpPost]
        public ActionResult LoginSessionLstFrm(string strAdminId, string strIPAddr)
        {
            DataSet ds = objAdminDao.SearchAdminLoginSessionLst(strAdminId, strIPAddr);
            ViewBag.loginSesionList = ds.Tables[0];
            return View();
        }

        /// -------------------------------------------------------
        /// <summary>
        /// 로그인 실패 이력 리스트
        /// </summary>
        /// -------------------------------------------------------
        public ActionResult LoginFailLstFrm()
        {
            List<TAdminLoginFail> lstAdminLoginFail = new List<TAdminLoginFail>();
            TAdminLoginFail objAdminLoginFail = new TAdminLoginFail();
            DataSet ds = new DataSet();
            ds = objAdminDao.SearchAdminSessionFailLst("");
            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                TAdminLoginFail objAdminLoginFailLog = new TAdminLoginFail();
                objAdminLoginFailLog.TryYMD = Convert.ToDateTime(dr["TryYMD"]);
                objAdminLoginFailLog.AdminID = dr["AdminID"].ToString();
                objAdminLoginFailLog.TryCnt = Convert.ToByte(dr["TryCnt"]);
                objAdminLoginFailLog.ResetCnt = Convert.ToByte(dr["ResetCnt"]);
                objAdminLoginFailLog.HAdminID = dr["HAdminID"].ToString();
                objAdminLoginFailLog.RegDate = Convert.ToDateTime(dr["RegDate"]);
                objAdminLoginFailLog.UpdDate = (dr["UpdDate"] == DBNull.Value) ? (DateTime?)null : ((DateTime)dr["UpdDate"]);

                lstAdminLoginFail.Add(objAdminLoginFail);
            }
            objAdminLoginFail.AdminLoginFailGrid = lstAdminLoginFail;

            return View("LoginFailLstFrm", objAdminLoginFail);
        }

        [HttpPost]
        public ActionResult LoginFailLstFrm(string strAdminID)
        {
            List<TAdminLoginFail> lstAdminLoginFail = new List<TAdminLoginFail>();
            DataSet ds = new DataSet();
            ds = objAdminDao.SearchAdminSessionFailLst(strAdminID);


            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                TAdminLoginFail objAdminLoginFail = new TAdminLoginFail();
                objAdminLoginFail.TryYMD = Convert.ToDateTime(dr["TryYMD"]);
                objAdminLoginFail.AdminID = dr["AdminID"].ToString();
                objAdminLoginFail.TryCnt = Convert.ToByte(dr["TryCnt"]);
                objAdminLoginFail.ResetCnt = Convert.ToByte(dr["ResetCnt"]);
                objAdminLoginFail.HAdminID = dr["HAdminID"].ToString();
                objAdminLoginFail.RegDate = Convert.ToDateTime(dr["RegDate"]);
                objAdminLoginFail.UpdDate = (dr["UpdDate"] == DBNull.Value) ? (DateTime?)null : ((DateTime)dr["UpdDate"]);

                lstAdminLoginFail.Add(objAdminLoginFail);
            }
            return PartialView("_ShowLoginFailList", lstAdminLoginFail);
        }
        /// -------------------------------------------------------
        /// <summary>
        /// 관리자 로그 입력
        /// </summary>
        /// -------------------------------------------------------
        public JsonResult AdminLogInsert(TAdminLog objAdminLog)
        {
            return Json(objAdminDao.AddAdminLogData(objAdminLog), JsonRequestBehavior.AllowGet);
        }

        /// -------------------------------------------------------
        /// <summary>
        /// 관리자 로그 목록
        /// </summary>
        /// -------------------------------------------------------
        public ActionResult AdminLogLst()
        {
            DataSet ds = objAdminDao.ShowAdminLogData("", "");
            ViewBag.AdminLogList = ds.Tables[0];
            return View();
        }
        [HttpPost]
        public ActionResult AdminLogLst(string strAdminId, string strIPAddr)
        {
            DataSet ds = objAdminDao.ShowAdminLogData(strAdminId, strIPAddr);
            ViewBag.sesionList = ds.Tables[0];
            return View();
        }
    } 
}

Controllers/MenuController.cs
using BillAdmin.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
///===============================================================
/// <summary>
/// FileName : MenuController.cs
/// Description : 메뉴/권한 탭 컨트롤러
/// Copyright : 2020 by PayLetter Inc. All rights reserved.
/// Author : mh_kim@payletter.com, 2020-11-09
/// Modify History : Just Created.
/// </summary>
///================================================================
namespace BillAdmin.Controllers
{
    public class MenuController : Controller
    {
        #region DB 관리
        DataBaseAccess.MenuDAO menuDao = new DataBaseAccess.MenuDAO();
        #endregion

        /// -------------------------------------------------------
        /// <summary>
        ///  MenuGroup 페이지 : Show Menu Group List
        /// </summary>
        /// ------------------------------------------------------- 
        public ActionResult MenuGroupForm()
        {
            DataSet ds = menuDao.ShowMgroupDataALL();
            ViewBag.menuGrp = ds.Tables[0];

            return View();
        }

        /// -------------------------------------------------------
        /// <summary>
        ///  MenuGroup 페이지 : Insert Menu Group List
        /// </summary>
        /// ------------------------------------------------------- 
        public ActionResult MenuGroupInsert()
        {
            return View();
        }

        [HttpPost]
        public ActionResult MenuGroupInsert(string MenuGroupName, short MenuGroupSort, string UseFlag, string MenuGroupIcon)
        {
            TAdminMenuGroup objTadminMenuGroup = new TAdminMenuGroup();
            TAdminMgmt objTadminMgmt = new TAdminMgmt();

            HttpCookie cookie = new HttpCookie("AdminID", objTadminMgmt.AdminID);
            string strAdminID = cookie.Values["AdminID"];

            objTadminMenuGroup.AdminID = "payletter";
            objTadminMenuGroup.MenuGroupName = MenuGroupName;
            objTadminMenuGroup.MenuGroupSort = MenuGroupSort;
            objTadminMenuGroup.MenuGroupIcon = MenuGroupIcon;
            objTadminMenuGroup.UseFlag = UseFlag;
            
            return Json(menuDao.AddMgroupData(objTadminMenuGroup), JsonRequestBehavior.AllowGet);
        }

        /// -------------------------------------------------------
        /// <summary>
        ///  MenuGroup 페이지 : Delete Menu Group List
        /// </summary>
        /// ------------------------------------------------------- 
        public ActionResult MenuGroupDelete(int intMgroupNo)
        {
            menuDao.DeleteMgroupData(intMgroupNo);
            return RedirectToAction("MenuGroupForm");
        }

        /// -------------------------------------------------------
        /// <summary>
        ///  Menu 페이지 : Show Menu Dropdwon List
        /// </summary>
        /// -------------------------------------------------------       
        public ActionResult MenuForm()
        {
            MHKIM_BILL_DBEntities db = new MHKIM_BILL_DBEntities();
            TAdminMenu objAdminMenu = new TAdminMenu();

            var menuGroupList = db.TAdminMenuGroup.ToList().Where(a => a.UseFlag.Equals("Y"));

            objAdminMenu.MenuGroupList = (from d in menuGroupList
                                          select new SelectListItem
                                     {
                                         Value = d.MenuGroupNo.ToString(),
                                         Text = d.MenuGroupName
                                     }).ToList();

            List<TAdminMenu> lstAdminMenu = new List<TAdminMenu>();
            DataTable dtManager = new DataTable();

            menuDao.ShowMenuDataAll(dtManager);

            foreach (DataRow dtrow in dtManager.Rows)
            {
                TAdminMenu objAdminMenulogs = new TAdminMenu();
                objAdminMenulogs.MenuNo = Convert.ToInt16(dtrow["MenuNo"].ToString());
                objAdminMenulogs.MenuName = dtrow["MenuName"].ToString();
                objAdminMenulogs.MenuENName = dtrow["MenuENName"].ToString();
                objAdminMenulogs.MenuLink = dtrow["MenuLink"].ToString();
                objAdminMenulogs.MenuSort = Convert.ToInt16(dtrow["MenuSort"].ToString());
                objAdminMenulogs.AdminID = dtrow["AdminID"].ToString();

                objAdminMenulogs.RegDate = Convert.ToDateTime(dtrow["RegDate"].ToString());
                objAdminMenulogs.UpdDate = (dtrow["UpdDate"] == DBNull.Value) ? (DateTime?)null : ((DateTime)dtrow["UpdDate"]);
                lstAdminMenu.Add(objAdminMenulogs);
            }

            objAdminMenu.AdminMenuGrid = lstAdminMenu;

            return View("MenuForm", objAdminMenu);
        }

        /// -------------------------------------------------------
        /// <summary>
        ///  Menu 페이지 : Show Menu Dropdwon Filter List
        /// </summary>
        /// -------------------------------------------------------        
        public ActionResult MenuFilter(int intMenuGroupNo)
        {
            MHKIM_BILL_DBEntities db = new MHKIM_BILL_DBEntities();

            int? menuGroupNo = Convert.ToInt16(intMenuGroupNo);
            List<TAdminMenu> lstAdminMenu = new List<TAdminMenu>();

            var menuGroupList = db.TAdminMenuGroup.ToList();
            if (menuGroupNo.Equals(0))
            {
                DataTable dtManager = new DataTable();
                menuDao.ShowMenuDataAll(dtManager);
                foreach (DataRow dtrow in dtManager.Rows)
                {
                    TAdminMenu objAdminMenuLogs = new TAdminMenu();
                    objAdminMenuLogs.MenuNo = Convert.ToInt16(dtrow["MenuNo"].ToString());
                    objAdminMenuLogs.MenuName = dtrow["MenuName"].ToString();
                    objAdminMenuLogs.MenuENName = dtrow["MenuENName"].ToString();
                    objAdminMenuLogs.MenuLink = dtrow["MenuLink"].ToString();
                    objAdminMenuLogs.MenuSort = Convert.ToInt16(dtrow["MenuSort"].ToString());
                    objAdminMenuLogs.AdminID = dtrow["AdminID"].ToString();

                    objAdminMenuLogs.RegDate = Convert.ToDateTime(dtrow["RegDate"].ToString());
                    objAdminMenuLogs.UpdDate = (dtrow["UpdDate"] == DBNull.Value) ? (DateTime?)null : ((DateTime)dtrow["UpdDate"]); lstAdminMenu.Add(objAdminMenuLogs);
                }
            }
            else
            {
                DataTable dtManager = new DataTable();
                menuDao.ShowMenuDataManage(dtManager, intMenuGroupNo);
                foreach (DataRow dtrow in dtManager.Rows)
                {
                    TAdminMenu objAdminMenuLogs = new TAdminMenu();
                    objAdminMenuLogs.MenuNo = Convert.ToInt16(dtrow["MenuNo"].ToString());
                    objAdminMenuLogs.MenuName = dtrow["MenuName"].ToString();
                    objAdminMenuLogs.MenuENName = dtrow["MenuENName"].ToString();
                    objAdminMenuLogs.MenuLink = dtrow["MenuLink"].ToString();
                    objAdminMenuLogs.MenuSort = Convert.ToInt16(dtrow["MenuSort"].ToString());
                    objAdminMenuLogs.AdminID = dtrow["AdminID"].ToString();

                    objAdminMenuLogs.RegDate = Convert.ToDateTime(dtrow["RegDate"].ToString());
                    objAdminMenuLogs.UpdDate = (dtrow["UpdDate"] == DBNull.Value) ? (DateTime?)null : ((DateTime)dtrow["UpdDate"]); lstAdminMenu.Add(objAdminMenuLogs);
                }
            }
            return PartialView("_ShowMenuList", lstAdminMenu);
        }

        /// -------------------------------------------------------
        /// <summary>
        ///  Menu 페이지 : Update Menu Details Info
        /// </summary>
        /// -------------------------------------------------------
        public ActionResult MenuUpdate(TAdminMenu objAdminMenu)
        {
            return Json(menuDao.UpdMenuData(objAdminMenu), JsonRequestBehavior.AllowGet);
        }

        /// -------------------------------------------------------
        /// <summary>
        ///  Menu 페이지 : Delete Menu Details Info
        /// </summary>
        /// -------------------------------------------------------
        public ActionResult MenuDelete(int intMenuNo)
        {
            menuDao.DeleteMenuData(intMenuNo);
            return RedirectToAction("MenuForm");
        }

        /// -------------------------------------------------------
        /// <summary>
        ///  Menu 페이지 : Insert Menu Details Info
        /// </summary>
        /// -------------------------------------------------------
        public ActionResult MenuInsert(TAdminMenu objAdminMenu)
        {
            return Json(menuDao.AddMenuData(objAdminMenu), JsonRequestBehavior.AllowGet);
        }

        /// -------------------------------------------------------
        /// <summary>
        ///  MenuRole 페이지 : Show Menu Role Details Info
        /// </summary>
        /// -------------------------------------------------------
        public ActionResult MenuRoleForm(TAdminMenuRole objAdminMenuRole)
        {
            DataSet ds = menuDao.ShowMenuRoleData();
            ViewBag.menuRolelst = ds.Tables[0];

            return View();
        }

      
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title - Bill Admin</title>
    <!-- Custom fonts for this template-->
    @*<link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">*@
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
   
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "Home")">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">PAY LETTER </div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index", "Home")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>대쉬보드</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">



            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>메뉴/권한</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">

                        <a class="collapse-item" href="@Url.Action("MenuGroupForm", "Menu")" onclick="return AddMenuTabLog(1)">메뉴그룹</a>
                        <a class="collapse-item" href="@Url.Action("MenuForm", "Menu")" onclick="return AddMenuTabLog(2)">메뉴</a>
                        <a class="collapse-item" href="@Url.Action("MenuRoleForm", "Menu")" onclick="return AddMenuTabLog(3)">메뉴 역할</a>

                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>관리자/로그인</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("AdminFrm", "Admin")" onclick="return AddAdminTabLog(1)">관리자</a>
                        <a class="collapse-item" href="@Url.Action("AdminLogLst", "Admin")" onclick="return AddAdminTabLog(3)">관리자 로그</a>
                        <a class="collapse-item" href="@Url.Action("SessionLstFrm", "Admin")" onclick="return AddAdminTabLog(3)">실시간 세션</a>
                        <a class="collapse-item" href="@Url.Action("LoginFailLstFrm", "Admin")" onclick="return AddAdminTabLog(4)">로그인 실패 이력</a>
                        <a class="collapse-item" href="@Url.Action("LoginSessionLstFrm", "Admin")" onclick="return AddAdminTabLog(5)">로그인 세션 이력</a>
                    </div>
                </div>
            </li>
            

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>



                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@HttpContext.Current.User.Identity.Name</span>

                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <a class="dropdown-item" data-toggle="modal" data-target="#adminDetailInfoModal">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    관리자 상세 정보
                                </a>
                                <a class="dropdown-item" href="/Account/UpdateAdminPwdModal?strAdminId=@HttpContext.Current.User.Identity.Name">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    비밀번호 변경
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout

                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Admin Page 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="@Url.Action("LogOut", "Account")">Logout</a>
                </div>
            </div>
        </div>
    </div>
   
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>



    <script src="~/scripts/js/menu.js"></script>
    <script>
    function AddMenuTabLog(intMenuTabNo) {
        var getUrlData = {
            MenuLink: document.querySelector("#collapseTwo > div > a:nth-child(" + intMenuTabNo + ")").getAttribute("href")
        }
        $.ajax({
            url: "/Admin/AdminLogInsert",
            data: JSON.stringify(getUrlData),
            type: "POST",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                console.log("log insert success");
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        });
    }

    function AddAdminTabLog(intAdminTabNo) {
        var getUrlData = {
            MenuLink: document.querySelector("#collapseUtilities > div > a:nth-child(" + intAdminTabNo + ")").getAttribute("href")
        }
        $.ajax({
            url: "/Admin/AdminLogInsert",
            data: JSON.stringify(getUrlData.toString()),
            type: "POST",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                console.log("log insert success");
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        });
    }
    </script>
</body>

</html>

Views/Shared/_LayoutWitoutNav.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Bill Admin</title>
    <link href="~/styles/Index.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/styles/LoginRegisterStyle.css" rel="stylesheet" />
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>

    <style>
        .loader{
            border: 16px solid #f3f3f3; /* Light grey */
            border-top: 16px solid #3498db; /* Blue */
            border-radius: 50%;
            width: 120px;
            height: 120px;
            animation: spin 2s linear infinite;
            position: fixed;
            top:50%;
            left:50%;
            transform: translate(-50%, -50%)
        }
  
    </style>
</head>
<body>

    <div class="loader"></div>

    <div class="container body-content">
        @RenderBody()
    </div>


    <script>
        $(window).on('load', function () {
            $('.loader').fadeOut();
        });
    </script>
</body>
</html>